export const SHOW_AUTH_MODAL = "SHOW_AUTH_MODAL";
export const HIDE_AUTH_MODAL = "HIDE_AUTH_MODAL";

export const SHOW_UPLOAD_MODAL = "SHOW_UPLOAD_MODAL";
export const HIDE_UPLOAD_MODAL = "HIDE_UPLOAD_MODAL";

export const HIDE_ALL_MODALS = "HIDE_ALL_MODALS";
