export const FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST";
export const FETCH_POSTS_ERROR = "FETCH_POSTS_ERROR";
export const FETCH_POSTS_RESET = "FETCH_POSTS_RESET";

export const FETCH_ALL_POSTS_SUCCESS = "FETCH_ALL_POSTS_SUCCESS";
export const FETCH_OWN_POSTS_SUCCESS = "FETCH_OWN_POSTS_SUCCESS";

export const RESET_STATE = "RESET_STATE";

export const postTypes = {
  ALL_POSTS: "ALL_POSTS",
  OWN_POSTS: "OWN_POSTS",
};
